apiVersion: v1
kind: Service
metadata:
  name: spreadpro-updated
  namespace: nabla-genai
spec:
  type: NodePort
  ports:
    - port: 5173
      nodePort: 30690
      targetPort: 5173
      protocol: TCP
  selector:
    app: spreadpro-updated
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spreadpro-updated
  namespace: nabla-genai
  labels:
    app: spreadpro-updated
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spreadpro-updated
  template:
    metadata:
      labels:
        app: spreadpro-updated
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - worker
      containers:
        - name: spreadpro-updated-container
          image: 18.211.134.5:30302/spreadpro-updated:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 5173